# Arrays Introduction

In [2]:
import numpy as np

## 1D Array

In [3]:
n1=np.array([1,2,3,4,5])
print(n1)

[1 2 3 4 5]


## 2D array

In [4]:
n2 = np.array([[1,2,3],[4,5,6]])
print(n2)

[[1 2 3]
 [4 5 6]]


#### initialising with zeroes

In [5]:
n3 = np.zeros((3,4))
print(n3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### initialiosing with same number

In [6]:
n4 = np.full((2,3),7) ## 2x3 array with all elements as 7
print(n4)

[[7 7 7]
 [7 7 7]]


#### initialising with a range

In [7]:
n1=np.arange(10,20)
n2=np.arange(10,21,2) ## step size 2
print(n1)
print(n2)

[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18 20]


#### initialising with random numbers

In [8]:
n1 = np.random.randint(1,100,5) ## 5 random integers between 1 and 100
print(n1)

[21 57 65 64 54]


### checking and changing the shape 

In [9]:
n1 = np.array([[1,2,3,4],[5,6,7,8]])
print("Original array:")    
print(n1)
print("Shape of array:", n1.shape)
n2 = n1.reshape(4,2)
print("Reshaped array:")
print(n2)

Original array:
[[1 2 3 4]
 [5 6 7 8]]
Shape of array: (2, 4)
Reshaped array:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


##  joining arrays


#### vstack()

In [10]:

n1 = np.array([10,20,30 ])
n2 = np.array([40,50,60 ])
n3 = np.vstack((n1,n2)) 
## vertical stack used to stack arrays vertically
print(n3)

[[10 20 30]
 [40 50 60]]


#### hstack()

In [11]:
n1 = np.array([10,20,30 ])
n2 = np.array([40,50,60 ])
n3 = np.hstack((n1,n2)) 
## horizontal stack used to stack arrays horizontally
print(n3)

[10 20 30 40 50 60]


#### column_stack()

In [12]:
n1 = np.array([10,20,30 ])
n2 = np.array([40,50,60 ])
n3 = np.column_stack((n1,n2))
## column stack used to stack 1-D arrays as columns into 2-D array
print(n3)

[[10 40]
 [20 50]
 [30 60]]


# Intersection and Difference 

In [13]:
n1 = np.array([10,20,30,40,50])
n2 = np.array([30,40,50,60,70])
n3 = np.intersect1d(n1,n2)
## intersection of two arrays
print("Intersection:", n3)
n4 = np.setdiff1d(n1,n2)
## difference of two arrays
print("Difference:", n4)

Intersection: [30 40 50]
Difference: [10 20]


# Addition

In [14]:
n1 = np.array([[1,2,3,4],[5,6,7,8]])
n2 = np.array([[10,20,30,40],[50,60,70,80]])
n3 = np.sum([n1,n2], axis=0) # axis=0 for column-wise addition
n4 = np.sum([n1,n2], axis=1) # axis=1 for row-wise addition
print(" Col-wise addition of two arrays:")
print(n3)
print("Row-wise addition of two arrays:")
print(n4)

 Col-wise addition of two arrays:
[[11 22 33 44]
 [55 66 77 88]]
Row-wise addition of two arrays:
[[  6   8  10  12]
 [ 60  80 100 120]]


# Basic Array Mathematics

#### Addition

In [15]:
n1= np.array([[1,2,3],[4,5,6]])
n2= np.array([[10,20,30],[40,50,60]])
n3= n1 + n2
print("Addition of two arrays:")
print(n3)

Addition of two arrays:
[[11 22 33]
 [44 55 66]]


#### Subtraction

In [16]:
n1= np.array([[1,2,3],[4,5,6]])
n2= np.array([[10,20,30],[40,50,60]])
n3 = n1 - n2
print("Subtraction of two arrays:")
print(n3)

Subtraction of two arrays:
[[ -9 -18 -27]
 [-36 -45 -54]]


#### multiplication

In [17]:
n1= np.array([[1,2,3],[4,5,6]])
n2= np.array([[10,20,30],[40,50,60]])
n3 = n1*n2
print("Multiplication of two arrays:")
print(n3)

Multiplication of two arrays:
[[ 10  40  90]
 [160 250 360]]


#### Division

In [18]:
n1= np.array([[1,2,3],[4,5,6]])
n2= np.array([[10,20,30],[40,50,60]])
n3 = n1 / n2
print("Division of two arrays:")
print(n3)

Division of two arrays:
[[0.1 0.1 0.1]
 [0.1 0.1 0.1]]


## Basic math Functions

#### mean

In [19]:
n1 =np.array([[1,2,3],[4,5,6]])
n2 =np.mean(n1, axis=0) # column-wise mean
n3 =np.mean(n1, axis=1) # row-wise mean
print("Column-wise mean:", n2)
print("Row-wise mean:", n3)

Column-wise mean: [2.5 3.5 4.5]
Row-wise mean: [2. 5.]


#### standard deviation

In [20]:
n1 = np.array([[1,2,3],[4,5,6]])
n2 = np.std(n1, axis=0) # column-wise standard deviation
n3 = np.std(n1, axis=1) # row-wise standard deviation
print("Column-wise standard deviation:", n2)
print("Row-wise standard deviation:", n3)

Column-wise standard deviation: [1.5 1.5 1.5]
Row-wise standard deviation: [0.81649658 0.81649658]


#### Median

In [21]:
n1 = np.array([[1,2,3],[4,5,6]])
n2 = np.std(n1, axis=0) # column-wise standard deviation
n3 = np.std(n1, axis=1) # row-wise standard deviation
print("Column-wise standard deviation:", n2)
print("Row-wise standard deviation:", n3)

Column-wise standard deviation: [1.5 1.5 1.5]
Row-wise standard deviation: [0.81649658 0.81649658]


# Saving and loadiing Numpy arrays

In [22]:
n1 = np.array([[1,2,3],[4,5,6]])
np.save('array_file.npy', n1)  # Saving the array to a file

In [23]:
n2 = np.load('array_file.npy')  # Loading the array from the file
print("Loaded array from file:")
print(n2)

Loaded array from file:
[[1 2 3]
 [4 5 6]]
