# Numpy Matrix

In [1]:
import numpy as np

In [2]:
n1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m1 = np.matrix(n1) ## Converting array to matrix
print("Numpy Array:\n", n1)
print("Numpy Matrix:\n", m1)

Numpy Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Numpy Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print(n1[0]) # Accessing first row of array
print(m1[0]) # Accessing first row of matrix


[1 2 3]
[[1 2 3]]


In [10]:
print(n1[:, 1]) # Accessing second column of array
print(m1[:, 1]) # Accessing second column of matrix
print(n1[:, 1:3]) # Accessing second and third column of array 
## first range is for rows and second range is for columns
print(m1[:, 1:3]) # Accessing second and third column of matrix

[2 5 8]
[[2]
 [5]
 [8]]
[[2 3]
 [5 6]
 [8 9]]
[[2 3]
 [5 6]
 [8 9]]


In [13]:
print(type(n1)) # <class 'numpy.ndarray'>
print(type(m1)) # <class 'numpy.matrix'>

<class 'numpy.ndarray'>
<class 'numpy.matrix'>


#### Transpose and multiplication of Matrices

In [12]:
m1.transpose()  # Transpose of matrix

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [14]:
n1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m1 = np.matrix(n1)
n2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
m2 = np.matrix(n2)

In [ ]:
n1.dot(n2)  # Matrix multiplication using arrays

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [18]:
m1 * m2  # Matrix multiplication using matrices

matrix([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]])